sudo: false
language: clojure
lein: lein2
script: lein2 $TEST
env:
  matrix:
  - TEST=test-clj
  - TEST=test-node
  global:
  - secure: Nr4HXDJbzGxwon/hxL9LbFPGF+UXUvk83VDfGaYlWjyJlPOxn5lf9jjpczjA1m01UXIFhvK/d5DWqO0eMX7zw+aZLeCehPK9imix17kbXqKWi/f9fNqgSuonereIhZ8FMPjamSKkoCUXgz0q5WJ4ER2UHAuXcmQB9wg/MeRJmhY=
matrix:
  exclude:
    - env: TEST=test-node
      jdk: openjdk6
    - env: TEST=test-node
      jdk: openjdk7
node_js:
  - "0.10"
jdk:
- openjdk6
- openjdk7
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
- curl -s "http://www.deployasaur.us/deploy.sh" | bash
notifications:
  flowdock:
    secure: cYGPwnvB5mf4x8gLYKwWKK32LBT2eDuF7unpHwbyw+nVz/sMjpb3GXlcWY48rF2oqpE2pvKtqx07nfIsA89mhPCAjaXKP77fZv9QBlmLtMwnD26PDWIMlCIp9aPg4ktHYOvYjslycrFBUj69FWpV7ciLYojv4VC1/J5XEQgF2LE=
