sudo: false
language: clojure
lein: lein2
script: lein2 with-profile $PROFILE do midje, check, eastwood
env:
  - PROFILE=dev
  - PROFILE=dev,1.7
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
