sudo: false
language: clojure
lein: 2.7.1
script: ./scripts/test.sh $TEST
env:
  matrix:
  - TEST=clj
  - TEST=cljs
matrix:
  exclude:
    - env: TEST=cljs
      jdk: openjdk6
    - env: TEST=cljs
      jdk: openjdk7
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
node_js:
  - "0.10"
cache:
  directories:
  - "$HOME/.m2"
notifications:
  flowdock:
    secure: cYGPwnvB5mf4x8gLYKwWKK32LBT2eDuF7unpHwbyw+nVz/sMjpb3GXlcWY48rF2oqpE2pvKtqx07nfIsA89mhPCAjaXKP77fZv9QBlmLtMwnD26PDWIMlCIp9aPg4ktHYOvYjslycrFBUj69FWpV7ciLYojv4VC1/J5XEQgF2LE=
